### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by XenoEmblems** [XenoEmblems/AniRec#1]
All I am trying to do is make my GET route work for my OMDB API
There is a lot of bugs that I am trying to fix and this is only one of them I need help..

/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/router/index.js:446
      throw new TypeError('Router.use() requires middleware function but got a
            ^
TypeError: Router.use() requires middleware function but got a Object
    at Function.<anonymous> (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/router/index.js:446:13)
    at Array.forEach (native)
    at Function.use (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/router/index.js:444:13)
    at EventEmitter.<anonymous> (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/application.js:216:21)
    at Array.forEach (native)
    at EventEmitter.use (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/application.js:213:7)
    at Object.<anonymous> (/Users/ericxavierdoyle/SoloProject/server.js:21:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
21 Apr 11:08:19 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by XenoEmblems** [comment]
@bigtone1284 @williamfshaw @h4w5 @hari @drrobotmck

**Comment by bigtone1284** [comment]
@XenoEmblems Eric, please resubmit your issue with this template:
https://github.com/ga-students/WDI_McClane/blob/master/project_02/asking_for_help.md

**Comment by ghost** [comment]
Also use correct markdown for code blocks: <pre>```</pre> before and after the code lines...

**Comment by bigtone1284** [comment]
@XenoEmblems Also, I took a look at your server.js and compare it to other server.js's from class.  

You have your routers in the public directory.

**Comment by XenoEmblems** [comment]
Sorry about that I will resubmit my issue once Kyle's lecture is over.

**Comment by bigtone1284** [comment]
Please close this issue.  We will deal with issue #2 :)
